### ISSUE TITLE
Are you serious?

### ISSUE THREAD

**Issue by xied75** [yobasystems/alpine-nginx#1]
Hi there, for your Dockerfiles that includes ssh, I failed to see where did you start your sshd? And you even didn't expose 22 at all. You sure your sshd is running when container starts?

**Comment by dominictayloruk** [comment]
No ssh daemon running or port 22 open. It isn't ssh access to the container, its ssh-key authentication for a git clone of the source repository to be served by Nginx. 

Basically if you have your website file in a git repo, that's private, you need to authenticate to have access. You can do this one of 2 ways;

1. By adding the username and password to the repo URL in the environment variable
````
git clone --depth=1 --branch=master ${REPO} /etc/nginx/html

REPO="https://mygitusername:myg1tpa55w0rd@github.com/user/repo"
````
OR

2. Also you can add a ssh private key so the password isn't in the request url, take a look at 
[git-ssh run script](https://github.com/yobasystems/alpine-nginx/blob/master/alpine-nginx-git-ssh/files/run.sh)
````
#add ssh private key for auth to git service of choice
mkdir -p ~/.ssh
echo "${SSH_PRIVATE_KEY}" | tr -d '\r' > ~/.ssh/id_rsa
chmod 600 ~/.ssh/id_rsa
#clone repo with passwordless auth
git clone --depth=1 --branch=master ${REPO} /etc/nginx/html

${SSH_PRIVATE_KEY}
````

This would correspond to a public key already in your account where your repo is, and authorise access to the repo allowing the container to pull the files at run time.

Why would you want sshd and port 22 open in a container?

I'm closing this as this isn't an issue or a feature request.

**Comment by xied75** [comment]
Thanks for the quick response, no I'm not requesting a feature, I Misunderstood what you mean when you say SSH, I thought you are enabling SSH server in the container, for the reason why people want do that, I'd say: plenty.

Best regards,
